version: "3"
services:
  backend:
    build:
      context: ./task-manager-backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./task-mananger-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
